### ISSUE TITLE
os_unfair_lock_lock when used with NetworkKit

### ISSUE THREAD

**Issue by siddharth952** [vmanot/Merge#4]
If a network call fails for some reason then it causes os_unfair_lock_lock(base).

eg. Use of @ReactorRepository() var repository: UserRepository

```
public func registerDevice() -> AnyPublisher<GenericRequestResponse, Error> {
        return serverSession
            .task(with: .registerDevice)
            .successPublisher
            .tryMap({ try $0.unwrap(GenericRequestResponse.self) })
            .eraseToAnyPublisher()
    }
    
        func task(for action: Action) -> ActionTask {
        switch action {
        case .registerDevice: do {
            return repository.registerDevice()
                // .receiveOnMainQueue() Adding this is also not helping
                .eraseToActionTask()
        }
```
This is due to usage (Merge package's ) sinkResult. As earlier removing it used to help get rid of this problem at other places.

Reactor Commit Used: [50cfa48](https://github.com/vmanot/Reactor/commit/50cfa48583c7025a75d16a2081f01eeb6724c326)
Merge Commit Used: [37ebf4b](https://github.com/vmanot/Merge/commit/37ebf4b7428f2ce96ddb3ead0ee2e7202982b311)

**Comment by siddharth952** [comment]
Stack trace
![Screenshot 2023-09-22 at 11 35 37 AM](https://github.com/vmanot/Merge/assets/40488679/4cf9fe12-9370-4fc7-8066-73da89a1a04d)

**Comment by fampaySiddharth** [comment]
Any updates on the same?

**Comment by vmanot** [comment]
This should be fixed now, please reopen if you encounter it again.
