### ISSUE TITLE
_TaskQueueActor nil' cannot initialize specified type '_OSUnfairLocked<OpaqueThrowingTask?>'

### ISSUE THREAD

**Issue by thanhnguyen198** [vmanot/Merge#5]
I have problem when update lastest verison. Could you help me check it?
![Screenshot 2024-05-30 at 08 45 28](https://github.com/vmanot/Merge/assets/102564688/46a7133d-53d2-41af-86ff-470d62059b7c)

**Comment by vmanot** [comment]
@thanhnguyen198 whoops, this should be fixed now - please update all your packages! (I'd forgotten to push an update to one of the package dependencies, [Swallow](https://github.com/vmanot/Swallow)).

**Comment by thanhnguyen198** [comment]
@vmanot Thanks for supported
